FROM python:3.10-slim

WORKDIR /app

COPY backend/requirements.txt requirements.txt

RUN python -m pip install --upgrade pip

RUN pip3 install -r requirements.txt --no-cache-dir

COPY foodgram/ .


CMD ["gunicorn", "foodgram.wsgi:application", "--bind", "0:8000" ]