apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: foodgram
  namespace: foodgram
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - foodgram.local
      secretName: foodgram-tls
  rules:
    - host: foodgram.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx
                port:
                  number: 80
