apiVersion: v1
kind: Secret
metadata:
  name: foodgram-secrets
  namespace: foodgram
type: Opaque
stringData:
  DB_ENGINE: "django.db.backends.postgresql"
  POSTGRES_DB: "foodgram"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DJANGO_SECRET_KEY: "supersecret"
  DEBUG: "True"
  ALLOWED_HOSTS: "localhost,127.0.0.1,backend,nginx,foodgram.local,*"
  CSRF_TRUSTED_ORIGINS: "http://foodgram.local"

